version: '3.8'

services:
  frontend:
    build: ./frontend
    container_name: vote-system-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      REACT_APP_BACKEND_URL: http://backend:8000

  backend:
    build: ./backend
    container_name: vote-system-backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      REACT_APP_BACKEND_URL: http://backend:8000
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres

  db:
    image: postgres:13
    container_name: vote-system-db
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: